ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
  ITERATOR_OPTIONS:
    MAX_SCENE_REPEAT_STEPS: -1
    MAX_SCENE_REPEAT_EPISODES: 10

SIMULATOR:
  TURN_ANGLE: 30
  TILT_ANGLE: 30
  ACTION_SPACE_CONFIG: "v1"
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR', 'SEMANTIC_SENSOR']
    HEIGHT: 0.88
    RADIUS: 0.18
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: False
  SEMANTIC_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    POSITION: [0, 0.88, 0]
  RGB_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    POSITION: [0, 0.88, 0]
  DEPTH_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    MIN_DEPTH: 0.5
    MAX_DEPTH: 5.0
    POSITION: [0, 0.88, 0]

TASK:
  TYPE: Nav-v0
  POSSIBLE_ACTIONS: ["STOP", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT", "LOOK_UP", "LOOK_DOWN"]
  SENSORS: ["OBJECTGOAL_SENSOR", "COMPASS_SENSOR", "GPS_SENSOR"]
  GOAL_SENSOR_UUID: objectgoal
  MEASUREMENTS: []

DATASET:
  TYPE: SemexpPolicyTraining
  SPLIT: train
  DATASET_TYPE: mp3d
  SCENE_TYPE: annotated
  DATA_PATH: "habitat-challenge-data/custom_objectgoal_{dataset_type}/{scene_type}_scenes/{split}/{split}.json.gz"
  SCENES_DIR: "habitat-challenge-data/data/scene_datasets/"
