BASE_TASK_CONFIG_PATH: challenge_objectnav2022.local.rgbd.yaml

AGENT_GPU_IDS: [0]        # IDs of GPUs to use for agent with DistributedDataParallel — each GPU corresponds to one agent process
SIMULATOR_GPU_IDS: [0]    # IDs of GPUs to use for vectorized environments
NO_GPU: 1                 # 1: ignore IDs above and run on CPU, 0: run on GPUs with IDs above
NUM_ENVIRONMENTS: 10      # number of environments (per agent process)
DUMP_LOCATION: data       # path to dump models and log
EXP_NAME: exp             # experiment name
MIXED_PRECISION_AGENT: 0  # 1: mixed precision agent, 0: fp32
VISUALIZE: 0              # 1: render observation and predicted semantic map, 0: no visualization
PRINT_IMAGES: 1           # 1: save visualization as images, 0: no image saving

ENVIRONMENT:
  num_sem_categories: 16  # number of semantic segmentation categories
  turn_angle: 30.0        # agent turn angle (in degrees)
  success_distance: 0.1   # success distance (in metres)
  frame_height: 480       # first-person frame height (in pixels)
  frame_width: 640        # first-person frame width (in pixels)
  camera_height: 0.88     # camera sensor height (in metres)
  hfov: 79.0              # horizontal field of view (in degrees)
  min_depth: 0.5          # minimum depth for depth sensor (in metres)
  max_depth: 5.0          # maximum depth for depth sensor (in metres)

AGENT:
  goal_update_steps: 1    # frequency at which to update the high-level goal during inference
  max_steps: 500          # maximum number of steps before stopping an episode

  SEMANTIC_MAP:
    map_size_cm: 4800        # global map size (in centimetres)
    map_resolution: 5        # size of map bins (in centimeters)
    vision_range: 100        # diameter of local map region visible by the agent (in cells)
    global_downscaling: 2    # ratio of global over local map
    du_scale: 4              # depth unit scale
    cat_pred_threshold: 5.0  # number of depth points to be in bin to classify it as a certain semantic category
    exp_pred_threshold: 1.0  # number of depth points to be in bin to consider it as explored
    map_pred_threshold: 1.0  # number of depth points to be in bin to consider it as obstacle

  PLANNER:
    collision_threshold: 0.20  # distance under which we consider there's a collision
    denoise_selem_radius: 0    # radius (in cells) of noise removal structuring element
    dilation_selem_radius: 1   # radius (in cells) of dilation structuring element

  POLICY:
    type: frontier  # one of "frontier" or "semantic"

  PRETRAINED_MODELS:
    segmentation_model_path: data/pretrained_models/segmentation/segmentation_model.pth
